<?php

$_lang['setting_mpc_base_section_name'] = 'Имя базовой секции';
$_lang['setting_mpc_base_section_name_desc'] = 'значение по умолчанию mpc_base.';
$_lang['setting_mpc_common_config_name'] = 'Имя общей конфигурации в интерфейсе MIGX';
$_lang['setting_mpc_common_config_name_desc'] = 'значение по умолчанию mpc_config. должно совпадать с именем TV';
$_lang['setting_mpc_config_tv_id'] = 'ID TV c общей конфигурацией страницы';
$_lang['setting_mpc_config_tv_id_desc'] = 'значение по умолчанию задается при установке';
$_lang['setting_mpc_contacts_page_id'] = 'ID страницы Контакты';
$_lang['setting_mpc_contacts_page_id_desc'] = 'значение по умолчанию задается при установке';
$_lang['setting_mpc_contacts_tv_name'] = 'Имя TV для контактов';
$_lang['setting_mpc_contacts_tv_name_desc'] = 'значение по умолчанию contacts';
$_lang['setting_mpc_contacts_tv_id'] = 'ID TV для контактов';
$_lang['setting_mpc_contacts_tv_id_desc'] = 'значение по умолчанию задается при установке';
$_lang['setting_mpc_fake_img_path'] = 'Путь к изображению-заглушке';
$_lang['setting_mpc_fake_img_path_desc'] = 'изображение заполнитель для lazyload';
$_lang['setting_mpc_lazyload_attr'] = 'Атрибут для LazyLoad';
$_lang['setting_mpc_lazyload_attr_desc'] = 'если оставить пустым, lazyload работать не будет';
$_lang['setting_mpc_path_to_chunks'] = 'Путь к чанкам';
$_lang['setting_mpc_path_to_chunks_desc'] = 'значение по умолчанию chunks/. Задается относительно пути в настройке pdotools_elements_path.';
$_lang['setting_mpc_path_to_dist'] = 'Путь к распарсенным страницам';
$_lang['setting_mpc_path_to_dist_desc'] = 'значение по умолчанию parsed/. Задается относительно пути в настройке pdotools_elements_path.';
$_lang['setting_mpc_path_to_presets'] = 'Путь к пресетам';
$_lang['setting_mpc_path_to_presets_desc'] = 'значение по умолчанию presets/';
$_lang['setting_mpc_path_to_sections'] = 'Путь к секциям';
$_lang['setting_mpc_path_to_sections_desc'] = 'значение по умолчанию sections/. Задается относительно пути в настройке pdotools_elements_path.';
$_lang['setting_mpc_path_to_src'] = 'Путь к размеченной верстке';
$_lang['setting_mpc_path_to_src_desc'] = 'значение по умолчанию templates/. Задается относительно папки core/ сайта.';
$_lang['setting_mpc_phone_format'] = 'Формат номера телефона';
$_lang['setting_mpc_phone_format_desc'] = 'значение по умолчанию 8 (\2) \3-\4-\5';
$_lang['setting_mpc_phone_regexp'] = 'Формат регулярка для форматирования телефона';
$_lang['setting_mpc_phone_regexp_desc'] = 'значение по умолчанию /(\d)(\d{3})(\d{3})(\d{2})(\d{2})$/';
$_lang['setting_mpc_static_block_page_id'] = 'ID страницы с Типами страниц';
$_lang['setting_mpc_static_block_page_id_desc'] = 'значение по умолчанию задается при установке';
$_lang['setting_mpc_tmplvar_ids'] = 'Список ID TV для добавления создаваемым шаблонам';
$_lang['setting_mpc_tmplvar_ids_desc'] = 'значение по умолчанию задается при установке';
$_lang['setting_mpc_tpl_file_extension'] = 'Расширение файлов с вёрсткой';
$_lang['setting_mpc_tpl_file_extension_desc'] = 'значение по умолчанию .tpl';
$_lang['setting_mpc_wrapper_name'] = 'Имя секции-обёртки';
$_lang['setting_mpc_wrapper_name_desc'] = 'это базовая секция в которую заворачиваются все остальные секции.';
$_lang['setting_mpc_path_to_samples'] = 'Путь к файлам-образцам';
$_lang['setting_mpc_path_to_samples_desc'] = 'значение по умолчанию components/migxpageconfigurator/elements/samples/';
$_lang['setting_mpc_dev_mode'] = 'Включить режим разработки?';
$_lang['setting_mpc_dev_mode_desc'] = 'в этом режиме при каждом запуске mgr_tpl.php очищается кэш';
$_lang['setting_mpc_common_thumb_params'] = 'Общие параметры создания миниатюр';
$_lang['setting_mpc_common_thumb_params_desc'] = 'значение по умолчанию q=90&zc=1&f=webp';
$_lang['setting_mpc_thumb_snippet'] = 'Сниппет для создания миниатюр';
$_lang['setting_mpc_thumb_snippet_desc'] = 'значение по умолчанию mpcThumb (встроенная обёртка над pThumb). Для некэшируемого вызова добавьте перед названием сниппета знак !';
$_lang['setting_mpc_expand_attr'] = 'Атрибут для SVG картинок, которые нужно добавить в разметку';
$_lang['setting_mpc_expand_attr_desc'] = 'значение по умолчанию data-svg.';
$_lang['setting_mpc_download_paths'] = 'Пути к загружаемым файлам';
$_lang['setting_mpc_download_paths_desc'] = 'JSON с подпапкой для каждого типа медиа ОТНОСИТЕЛЬНО базового пути медиа (mpc_media_path) внутри источника. Пустое значение типа → используется имя типа (images/videos/audios/others). По умолчанию {"images":"","videos":"","audios":"","others":""}.';
$_lang['setting_mpc_lazyload_enabled'] = 'Включить ленивую загрузку?';
$_lang['setting_mpc_lazyload_enabled_desc'] = 'Глобальный выключатель lazyload. Выкл — JS ленивой загрузки не подключается, картинки грузятся сразу.';
$_lang['setting_mpc_expand_enabled'] = 'Включить разворачивание svg?';
$_lang['setting_mpc_expand_enabled_desc'] = 'Глобальный выключатель разворачивания SVG (data-svg → инлайн-svg). Выкл — svg не разворачиваются.';
$_lang['setting_mpc_use_lexicons'] = 'Сохранять значения полей в словари?';
$_lang['setting_mpc_use_lexicons_desc'] = 'Режим лексиконов: переводимые значения полей выносятся в lexicon-файлы (в конфиге остаётся ключ) — даёт мультиязычность. После включения перенарезать.';
$_lang['setting_mpc_exclude_lexicons_filename'] = 'Путь к файлу со списком полей, которые не нужно переводить';
$_lang['setting_mpc_exclude_lexicons_filename_desc'] = 'файл следует располагать в папке core/ и путь указывать относительно этой папки.';
$_lang['setting_mpc_translated_content'] = 'Типы контента, которые нуждаются в переводе';
$_lang['setting_mpc_translated_content_desc'] = 'доступные значения: text,image,poster,video,audio,contact';
$_lang['setting_mpc_lexicon_filename_field'] = 'Поле которое будет использоваться в имени файла словаря';
$_lang['setting_mpc_lexicon_filename_field_desc'] = 'Допустимо только: alias — для сайтов с одинаковой структурой в разных контекстах; id — для сайтов с разной структурой. Любое иное значение трактуется как id.';
$_lang['setting_mpc_lexicon_path'] = 'Путь к лексиконам относительно корня сайта';
$_lang['setting_mpc_lexicon_path_desc'] = 'значение по умолчанию components/migxpageconfigurator/lexicon/';
$_lang['setting_mpc_lexicons_namespace'] = 'Пространство имён в котором нужно сохранять генерируемые лексиконы';
$_lang['setting_mpc_lexicons_namespace_desc'] = 'значение по умолчанию migxpageconfigurator';
$_lang['setting_mpc_available_languages'] = 'Доступные языки';
$_lang['setting_mpc_available_languages_desc'] = 'Список языков сайта через запятую (культуры). Пусто — один язык. Для всех перечисленных синхронизируется набор lexicon-ключей.';
$_lang['setting_mpc_default_language'] = 'Язык по умолчанию';
$_lang['setting_mpc_default_language_desc'] = 'Культура языка по умолчанию (по умолчанию ru). В её lexicon-файл пишутся значения при нарезке; остальные языки берут их как плейсхолдер до перевода.';
$_lang['setting_mpc_manifests_path'] = 'Путь к манифестам mpc CLI';
$_lang['setting_mpc_manifests_path_desc'] = 'Относительно папки core/ или абсолютный. Переопределяется переменной окружения MPC_MANIFESTS_PATH.';
$_lang['setting_mpc_allowed_tags'] = 'Тэги разрешённые в лексиконах';
$_lang['setting_mpc_allowed_tags_desc'] = 'HTML-теги, которые НЕ вырезаются при записи значения в лексикон (strip_tags), через запятую. Пусто — все теги вырезаются.';
$_lang['setting_mpc_allow_modx_tags'] = 'Разрешить тэги Fenom и Modx в лексиконах';
$_lang['setting_mpc_allow_modx_tags_desc'] = 'Разрешить хранить в лексиконах теги MODX/Fenom ([[…]], {…}). По умолчанию выкл — такие теги экранируются, чтобы не выполнялись из перевода.';
$_lang['setting_mpc_download_extensions'] = 'Разрешенные к автозагрузке расширения файлов';
$_lang['setting_mpc_download_extensions_desc'] = 'список расширений разделенных запятыми; по умолчанию jpg,jpeg,png,webp,mp4,mp3,txt';

$_lang['mpc_err_no_file']          = 'Файл не загружен';
$_lang['mpc_err_invalid_filetype'] = 'Допустимы только файлы .xlsx или .zip';
$_lang['mpc_err_cannot_read_file'] = 'Не удалось прочитать файл';
$_lang['mpc_err_no_filename']      = 'Не указано имя файла';
$_lang['mpc_err_no_lexicons']      = 'Файлы лексиконов не найдены';
$_lang['mpc_err_zip_create']       = 'Не удалось создать ZIP-архив';
$_lang['mpc_err_missing_params']   = 'Не указаны обязательные параметры';
$_lang['mpc_err_invalid_lang']     = 'Недопустимый код языка';
$_lang['mpc_err_file_not_found']   = 'Файл [[+file]] не найден, проверьте имя файла';

$_lang['setting_mpc_edit_mode'] = 'Режим редактирования (mpcVisualEditor)';
$_lang['setting_mpc_edit_mode_desc'] = 'Если включено — при нарезке создаются _edit-варианты чанков секций с сохранёнными data-mpc-* маркерами (нужны фронт-редактору mpcVE). После включения перенарезать. На прод-рендер не влияет.';
$_lang['setting_mpc_media_source'] = 'Источник файлов для медиа';
$_lang['setting_mpc_media_source_desc'] = 'Единый источник (modMediaSource), куда загружаются все скачанные медиа. Пусто — используется источник по умолчанию (default_media_source).';
$_lang['setting_mpc_media_path'] = 'Базовый путь медиа в источнике';
$_lang['setting_mpc_media_path_desc'] = 'Относительный путь внутри источника, под которым создаются подпапки images/videos/audios. По умолчанию assets/components/migxpageconfigurator/media/.';
$_lang['setting_mpc_editable_resource_fields'] = 'Редактируемые поля ресурса';
$_lang['setting_mpc_editable_resource_fields_desc'] = 'Список (через запятую) нативных полей ресурса, которые разрешено писать через write-API (FieldWriter, type=rfield).';
$_lang['setting_mpc_protected_resource_fields'] = 'Защищённые поля ресурса';
$_lang['setting_mpc_protected_resource_fields_desc'] = 'Список (через запятую) полей, которые НЕ перезаписываются при граб-сторонней обработке data-mpc-rfield (структурные + alias/uri/template).';

// Названия кастомных типов ресурсов (показываются в админке вместо class_key)
$_lang['mpctype']                       = 'Тип страницы';
$_lang['mpctype_create_here']           = 'Создать тип страницы здесь';
$_lang['mpctypecollection']             = 'Коллекция типов';
$_lang['mpctypecollection_create_here'] = 'Создать коллекцию типов здесь';

// Кнопки «Дополнить / Перезаписать секции из типа» (тулбар MIGX-грида mpc_config)
$_lang['mpc_copy_sections_ok_merge']        = 'Добавлено секций из типа: %d';
$_lang['mpc_copy_sections_ok_overwrite']    = 'Секции перезаписаны из типа';
$_lang['mpc_copy_sections_ok_clear']        = 'Секции очищены';
$_lang['mpc_copy_sections_err_no_id']       = 'Не удалось определить ресурс';
$_lang['mpc_copy_sections_err_no_resource'] = 'Ресурс не найден';

// --- Заголовки групп настроек ---
$_lang['area_mpc_paths']    = 'Пути';
$_lang['area_mpc_media']    = 'Медиа';
$_lang['area_mpc_lexicons'] = 'Лексиконы и языки';
$_lang['area_mpc_contacts'] = 'Контакты';
$_lang['area_mpc_resource'] = 'Поля ресурса';
$_lang['area_mpc_general']  = 'Общие';

// --- Недостающие настройки ---
$_lang['setting_mpc_tv_category'] = 'Категория автосоздаваемых TV';
$_lang['setting_mpc_tv_category_desc'] = 'категория-владелец TV, создаваемых из data-mpc-tv. Пусто — категория самого пакета mpc.';
$_lang['setting_mpc_cmp_resource_label_field'] = 'Поле-подпись ресурса в интерфейсе лексиконов';
$_lang['setting_mpc_cmp_resource_label_field_desc'] = 'поле ресурса, показываемое как подпись в CMP экспорта/импорта лексиконов. По умолчанию pagetitle.';
$_lang['setting_mpc_contact_lexicon_fields'] = 'Переводимые поля контакта';
$_lang['setting_mpc_contact_lexicon_fields_desc'] = 'под-поля контакта, которые лексиконятся (caption/value/fvalue/attributes через запятую). По умолчанию caption.';
$_lang['setting_mpc_exclude_fields_path'] = 'Путь к файлу служебных полей секции';
$_lang['setting_mpc_exclude_fields_path_desc'] = 'JSON со списком служебных полей, исключаемых из контента при рендере. Путь относительно папки core/.';
$_lang['setting_mpc_mime_to_ext_path'] = 'Путь к карте MIME→расширение';
$_lang['setting_mpc_mime_to_ext_path_desc'] = 'JSON-файл соответствия MIME-типов расширениям (для URL без расширения). Путь относительно папки core/.';
