<?php

$_lang['setting_mpc_debug'] = 'Enable logging (mxLogger)?';
$_lang['setting_mpc_debug_desc'] = 'Operational/debug records are written to mxLogger (if installed). Default: No.';
$_lang['setting_mpc_log_level'] = 'Minimum log level';
$_lang['setting_mpc_log_level_desc'] = 'Records below this level are dropped: debug, info, warning, error. Default: debug. Requires mxLogger.';
$_lang['setting_mpc_base_section_name'] = 'Name of the base section';
$_lang['setting_mpc_base_section_name_desc'] = 'the default value is mpc_base.';
$_lang['setting_mpc_common_config_name'] = 'Name of the shared configuration in the interface MIGX';
$_lang['setting_mpc_common_config_name_desc'] = 'the default value is mpc_config. must match the name of the TV';
$_lang['setting_mpc_config_tv_id'] = 'ID TV with the general configuration of the page';
$_lang['setting_mpc_config_tv_id_desc'] = 'the default value is set during installation';
$_lang['setting_mpc_contacts_page_id'] = 'Contact Page ID';
$_lang['setting_mpc_contacts_page_id_desc'] = 'the default value is set during installation';
$_lang['setting_mpc_contacts_tv_name'] = 'TV name for contacts';
$_lang['setting_mpc_contacts_tv_name_desc'] = 'the default value is contacts';
$_lang['setting_mpc_contacts_tv_id'] = 'TV ID for contacts';
$_lang['setting_mpc_contacts_tv_id_desc'] = 'the default value is set during installation';
$_lang['setting_mpc_fake_img_path'] = 'The path to the stub image';
$_lang['setting_mpc_fake_img_path_desc'] = 'image placeholder for lazyload';
$_lang['setting_mpc_lazyload_attr'] = 'Attribute for LazyLoad';
$_lang['setting_mpc_lazyload_attr_desc'] = 'if left empty, lazyload will not work';
$_lang['setting_mpc_path_to_chunks'] = 'Path to chunks';
$_lang['setting_mpc_path_to_chunks_desc'] = 'the default value is chunks/. Set relative to the path in the pdotools_elements_path setting.';
$_lang['setting_mpc_path_to_dist'] = 'The path to the steamed pages';
$_lang['setting_mpc_path_to_dist_desc'] = 'the default value is parsed/. Set relative to the path in the pdotools_elements_path setting.';
$_lang['setting_mpc_path_to_presets'] = 'Path to Presets';
$_lang['setting_mpc_path_to_presets_desc'] = 'default value presets/';
$_lang['setting_mpc_path_to_sections'] = 'Path to sections';
$_lang['setting_mpc_path_to_sections_desc'] = 'the default value is sections/. Set relative to the path in the pdotools_elements_path setting.';
$_lang['setting_mpc_path_to_src'] = 'The path to the marked layout';
$_lang['setting_mpc_path_to_src_desc'] = 'the default value is templates/. Set relative to pdotools_elements_path.';
$_lang['setting_mpc_phone_format'] = 'Phone number format';
$_lang['setting_mpc_phone_format_desc'] = 'default value 8 (\2) \3-\4-\5';
$_lang['setting_mpc_phone_regexp'] = 'Regular format for formatting the phone';
$_lang['setting_mpc_phone_regexp_desc'] = 'default value /(\d)(\d{3})(\d{3})(\d{2})(\d{2})$/';
$_lang['setting_mpc_static_block_page_id'] = 'Page ID with Page Types';
$_lang['setting_mpc_static_block_page_id_desc'] = 'the default value is set during installation';
$_lang['setting_mpc_tmplvar_ids'] = 'List of TV IDs to add by the created template';
$_lang['setting_mpc_tmplvar_ids_desc'] = 'the default value is set during installation';
$_lang['setting_mpc_tpl_file_extension'] = 'Extension of files with layout';
$_lang['setting_mpc_tpl_file_extension_desc'] = 'default value .tpl';
$_lang['setting_mpc_wrapper_name'] = 'Name of the wrapper section';
$_lang['setting_mpc_wrapper_name_desc'] = 'this is the base section in which all the other sections are wrapped.';
$_lang['setting_mpc_path_to_samples'] = 'Path to sample files';
$_lang['setting_mpc_path_to_samples_desc'] = 'default value components/migxpageconfigurator/elements/samples/';
$_lang['setting_mpc_dev_mode'] = 'Enable development mode?';
$_lang['setting_mpc_dev_mode_desc'] = 'in this mode, each time mgr_tpl.php is launched, the cache is cleared';
$_lang['setting_mpc_common_thumb_params'] = 'General Thumbnail Creation Options';
$_lang['setting_mpc_common_thumb_params_desc'] = 'default value q=90&zc=1&f=webp';
$_lang['setting_mpc_thumb_snippet'] = 'Snippet for creating thumbnails';
$_lang['setting_mpc_thumb_snippet_desc'] = 'default value is mpcThumb (bundled wrapper over pThumb). For a non-cacheable call, prefix the snippet name with a !';
$_lang['setting_mpc_expand_attr'] = 'Attribute for SVG images that need to be added to the markup';
$_lang['setting_mpc_expand_attr_desc'] = 'default value data-svg.';
$_lang['setting_mpc_download_paths'] = 'Paths to downloadable files';
$_lang['setting_mpc_download_paths_desc'] = 'JSON with a subfolder for each media type RELATIVE to the media base path (mpc_media_path) inside the source. Empty value for a type → the type name is used (images/videos/audios/others). Default {"images":"","videos":"","audios":"","others":""}.';
$_lang['setting_mpc_download_extensions'] = 'Allowed file extensions for auto-download';
$_lang['setting_mpc_download_extensions_desc'] = 'comma-separated list of extensions; default: jpg,jpeg,png,webp,mp4,mp3,txt';
$_lang['setting_mpc_lazyload_enabled'] = 'Enable lazy loading?';
$_lang['setting_mpc_lazyload_enabled_desc'] = 'Global lazyload switch. Off — the lazy-load JS is not loaded, images load immediately.';
$_lang['setting_mpc_expand_enabled'] = 'Enable svg expansion?';
$_lang['setting_mpc_expand_enabled_desc'] = 'Global SVG-expansion switch (data-svg → inline svg). Off — SVGs are not expanded.';
$_lang['setting_mpc_use_lexicons'] = 'Save field values to dictionaries?';
$_lang['setting_mpc_use_lexicons_desc'] = 'Lexicon mode: translatable field values are moved to lexicon files (config keeps the key) — enables multilingual content. Re-cut after enabling.';
$_lang['setting_mpc_exclude_lexicons_filename'] = 'File path with a list of fields that do not need to be translated';
$_lang['setting_mpc_exclude_lexicons_filename_desc'] = 'file should be located in the core/ folder and the path should be relative to that folder';
$_lang['setting_mpc_translated_content'] = 'Types of content that need translation';
$_lang['setting_mpc_translated_content_desc'] = 'available values: text,image,poster,video,audio,contact';
$_lang['setting_mpc_lexicon_filename_field'] = 'The field to be used in the lexicon file name';
$_lang['setting_mpc_lexicon_filename_field_desc'] = 'Allowed only: alias — for sites with the same structure across contexts; id — for sites with different structure. Any other value is treated as id.';
$_lang['setting_mpc_lexicon_path'] = 'The path to lexicons relative to the root of the site';
$_lang['setting_mpc_lexicon_path_desc'] = 'default value components/migxpageconfigurator/lexicon/';
$_lang['setting_mpc_lexicons_namespace'] = 'Namespace in which to store generated lexicons';
$_lang['setting_mpc_lexicons_namespace_desc'] = 'default value migxpageconfigurator';
$_lang['setting_mpc_available_languages'] = 'Available languages';
$_lang['setting_mpc_available_languages_desc'] = 'Comma-separated list of site languages (cultures). Empty — single language. The lexicon key set is synced for all listed.';
$_lang['setting_mpc_default_language'] = 'Default language';
$_lang['setting_mpc_default_language_desc'] = 'Default language culture (default ru). Its lexicon file gets values on cutting; other languages use them as a placeholder until translated.';
$_lang['setting_mpc_lang_cookie_name'] = 'Language cookie name';
$_lang['setting_mpc_lang_cookie_name_desc'] = 'Name of the cookie that stores the selected language (default mpc_lang). Same name on domain and subdomains → shared language; set a different name via a context setting to make subdomain languages independent.';
$_lang['setting_mpc_lang_cookie_domain'] = 'Language cookie domain';
$_lang['setting_mpc_lang_cookie_domain_desc'] = 'Domain the language cookie is set on. Empty — current host (http_host). Set a base domain with a leading dot (e.g. .site.ru) to make the cookie available on all subdomains.';
$_lang['setting_mpc_manifests_path'] = 'mpc CLI manifests path';
$_lang['setting_mpc_manifests_path_desc'] = 'Relative to core/ or absolute. Overridden by the MPC_MANIFESTS_PATH environment variable.';
$_lang['setting_mpc_allowed_tags'] = 'Tags allowed in lexicons';
$_lang['setting_mpc_allowed_tags_desc'] = 'HTML tags NOT stripped when writing a value to a lexicon (strip_tags), comma-separated. Empty — all tags are stripped.';
$_lang['setting_mpc_allow_modx_tags'] = 'Allow Fenom and Modx tags in lexicons';
$_lang['setting_mpc_allow_modx_tags_desc'] = 'Allow MODX/Fenom tags ([[…]], {…}) to be stored in lexicons. Off by default — such tags are escaped so they do not execute from a translation.';

$_lang['mpc_err_no_file']          = 'No file uploaded';
$_lang['mpc_err_invalid_filetype'] = 'Only .xlsx or .zip files are accepted';
$_lang['mpc_err_cannot_read_file'] = 'Cannot read file';
$_lang['mpc_err_no_filename']      = 'Filename required';
$_lang['mpc_err_no_lexicons']      = 'No lexicon files found';
$_lang['mpc_err_zip_create']       = 'Cannot create ZIP archive';
$_lang['mpc_err_missing_params']   = 'Missing required parameters';
$_lang['mpc_err_invalid_lang']     = 'Invalid language code';
$_lang['mpc_err_file_not_found']   = 'File [[+file]] not found, check the filename';

$_lang['setting_mpc_edit_mode'] = 'Edit mode (mpcVisualEditor)';
$_lang['setting_mpc_edit_mode_desc'] = 'When enabled, the cutter also writes _edit variants of section chunks keeping data-mpc-* markers (needed by the mpcVE frontend editor). Re-cut after enabling. Does not affect production render.';
$_lang['setting_mpc_media_source'] = 'Media file source';
$_lang['setting_mpc_media_source_desc'] = 'Single media source (modMediaSource) where all downloaded media go. Empty = use default_media_source.';
$_lang['setting_mpc_media_path'] = 'Media base path in source';
$_lang['setting_mpc_media_path_desc'] = 'Relative path inside the source under which images/videos/audios subfolders are created. Default assets/components/migxpageconfigurator/media/.';
$_lang['setting_mpc_editable_resource_fields'] = 'Editable resource fields';
$_lang['setting_mpc_editable_resource_fields_desc'] = 'Comma-separated list of native resource fields writable via the write-API (FieldWriter, type=rfield).';
$_lang['setting_mpc_protected_resource_fields'] = 'Protected resource fields';
$_lang['setting_mpc_protected_resource_fields_desc'] = 'Comma-separated list of fields NOT overwritten by grab-side data-mpc-rfield handling (structural + alias/uri/template).';

// Custom resource type names (shown in manager instead of class_key)
$_lang['mpctype']                       = 'Page type';
$_lang['mpctype_create_here']           = 'Create page type here';
$_lang['mpctypecollection']             = 'Types collection';
$_lang['mpctypecollection_create_here'] = 'Create types collection here';

// "Append / Overwrite sections from type" buttons (mpc_config MIGX grid toolbar)
$_lang['mpc_copy_sections_ok_merge']        = 'Sections added from type: %d';
$_lang['mpc_copy_sections_ok_overwrite']    = 'Sections overwritten from type';
$_lang['mpc_copy_sections_ok_clear']        = 'Sections cleared';
$_lang['mpc_copy_sections_err_no_id']       = 'Could not determine resource';
$_lang['mpc_copy_sections_err_no_resource'] = 'Resource not found';

// --- Settings area headers ---
$_lang['area_mpc_paths']    = 'Paths';
$_lang['area_mpc_media']    = 'Media';
$_lang['area_mpc_lexicons'] = 'Lexicons & languages';
$_lang['area_mpc_contacts'] = 'Contacts';
$_lang['area_mpc_resource'] = 'Resource fields';
$_lang['area_mpc_general']  = 'General';

// --- Missing settings ---
$_lang['setting_mpc_tv_category'] = 'Category for auto-created TVs';
$_lang['setting_mpc_tv_category_desc'] = 'owner category for TVs created from data-mpc-tv. Empty = the mpc package own category.';
$_lang['setting_mpc_cmp_resource_label_field'] = 'Resource label field in lexicons UI';
$_lang['setting_mpc_cmp_resource_label_field_desc'] = 'resource field shown as label in the lexicon export/import CMP. Default pagetitle.';
$_lang['setting_mpc_contact_lexicon_fields'] = 'Translatable contact fields';
$_lang['setting_mpc_contact_lexicon_fields_desc'] = 'contact sub-fields that get lexiconized (caption/value/fvalue/attributes, comma-separated). Default caption.';
$_lang['setting_mpc_exclude_fields_path'] = 'Path to section service-fields file';
$_lang['setting_mpc_exclude_fields_path_desc'] = 'JSON list of service fields excluded from content at render. Path relative to the core/ folder.';
$_lang['setting_mpc_mime_to_ext_path'] = 'Path to MIME-to-extension map';
$_lang['setting_mpc_mime_to_ext_path_desc'] = 'JSON file mapping MIME types to extensions (for URLs without an extension). Path relative to the core/ folder.';
